### ISSUE TITLE
[第二次作业-问题2]题面中的“若m已给出但过小”如何定义过小？如果小于round_up(3×σ)*2 + 1就算过小吗？还是怎么定义呢？如果过小需要给出警告信息提示，提示之后是要求继续重新输入吗？还是直接用标准公式计算出的m进行替换即可呢？

### ISSUE THREAD

**Issue by yutan1997** [UCAS-IPA/IPA-discuss#11]
### 问题描述
题面中的“若m已给出但过小”如何定义过小？如果小于round_up(3×σ)*2 + 1就算过小吗？还是怎么定义呢？如果过小需要给出警告信息提示，提示之后是要求继续重新输入吗？还是直接用标准公式计算出的m进行替换即可呢？

**Comment by zhongliqun** [comment]
当m小于round_up(3×σ)*2 + 1时，则认为m过小，需要给出警告信息，并立即终止程序，重新输入m。
