### ISSUE TITLE
[第二次作业-问题1]有关使用基于numpy的矩阵实现的问题

### ISSUE THREAD

**Issue by caryleo** [UCAS-IPA/IPA-discuss#13]
### 问题描述
请问我在使用基于numpy的矩阵实现时，对图像卷积的部分，我是否可以直接使用numpy库中的函数完成对卷积核的翻转，以及在取出当前卷积位置对应的子矩阵后，直接用子矩阵与核进行元素级相乘（numpy的实现中，直接为`A * B`），而非手工设置两层循环实现上述两部过程（即手工访问每一个元素）呢？谢谢。
### 相关文件
无

**Comment by zhongliqun** [comment]
翻转，矩阵的相关计算，依个人情况而定，没有特定限制。本次作业，要求像素填补，图像卷积，图像滤波不可直接调用现成函数，需手动写，细节部分的实现没有特别要求。
