### ISSUE TITLE
[第二次作业] 请问处理的图像是选取之前的一个灰度图像即可还是要把每张都处理展示一遍

### ISSUE THREAD

**Issue by mxy2097** [UCAS-IPA/IPA-discuss#14]
### 问题描述
请问处理的图像是选取之前的一个灰度图像即可还是要把每张都处理展示一遍？是选取一张灰度图片进行sig=1,2,3,5的四种处理还是要对之前的那些图片都进行这样的处理呢？相当于一共处理16次图片在程序里展示吗

**Comment by ijinjay** [comment]
不做数量限制，至少处理一张图像并在报告中展示说明。算法写得好，应该可以扩展应用到更多图像上。 😃
