### ISSUE TITLE
[第二次作业-问题3] opencv(python)中的高斯滤波函数。uint8的输入和float64的输入导致输出不一致

### ISSUE THREAD

**Issue by GuangyaoZhang** [UCAS-IPA/IPA-discuss#20]
### 问题描述
opencv（python）的高斯滤波函数输入为uint8和float64的时候输出是不一致的。
```python
import cv2
import numpy as np
lena512color_average = cv2.imread("lena512color_NTSC.tif")[:,:,0]
gaussian_out= cv2.GaussianBlur(lena512color_average,(7,7),sigmaX=1,borderType=cv2.BORDER_CONSTANT)
lena512color_average = np.array(lena512color_average,dtype="float64")
gaussian_out_2= cv2.GaussianBlur(lena512color_average,(7,7),sigmaX=1,borderType=cv2.BORDER_CONSTANT)
print(gaussian_out-gaussian_out_2)
```
实验表明，输入dtype为float64和uint8的numpy矩阵，对应的高斯滤波结果不同，差距不大，分布在-1到1左右的区间。视觉效果无差别。

为什么输入类型不同的话高斯滤波结果会不同呢？我们应该使用哪一种数据类型的结果呢？
### 相关文件
使用[GIST](https://gist.github.com/)来上传相关的长文件，然后链接到此处。

**Comment by zhongliqun** [comment]
最好用 float64 格式，精度比 uint8 更高。
关于结果不一致，很有可能将 uint8 数据带入计算时，有数据溢出（uint8类型最大只能表示255，超出255的，计算机一律按255处理），这样很容易产生精度误差，因此对图像数据做计算处理时，一般先转为更高精度类型。
