### ISSUE TITLE
[第二次作业-问题1]为什么要让矩阵与图像做卷积运算？

### ISSUE THREAD

**Issue by ChiChunan** [UCAS-IPA/IPA-discuss#22]
想问一下，为什么做图像处理的时候要让矩阵和图像做卷积？我尝试做均匀滤波，或者使用Laplacian算子和Sobel算子做微分时让核矩阵与图像直接对应做运算，而不是想卷积那样倒过来再运算，最后的结果好像都能达到我要的效果。所以为什么要卷积呢？是目前学的太浅，卷积的优势不明显吗？

**Comment by zhongliqun** [comment]
你所说的均匀滤波，Laplacian算子和Sobel算子都属卷积运算，只是卷积核各不相同，其本质都是卷积操作（卷积核与图像直接对应运算）。不太明白你理解的卷积操作是什么。参考下图的卷积示意图，希望能对你有所帮助。
![image](https://user-images.githubusercontent.com/55579451/66690777-e4ed1a80-ecc4-11e9-97f4-86dbb776ef1d.png)

**Comment by ChiChunan** [comment]
谢谢学长的解答。还有一点不明白，卷积运算前不是应该有一个翻转的操作吗？一维上，直观的说就是，算的时候应该让卷积序列的最后一个元素跟被卷积序列的第一个相乘，然后一直平移过去。但是我在做作业的时候发现，有没有这个翻转的操作好像对结果没什么影响，我直接让第一个和第一个乘，第二个和第二个乘。。。。也可以滤波啊

**Comment by zhongliqun** [comment]
正常情况，卷积操作需要对核函数翻转后，再对应相乘，但我们常见的卷积核（如均匀滤波，高斯滤波）都是对称矩阵，翻转后值不变，所以可直接跳过翻转环节。
