### ISSUE TITLE
[第二次作业-问题1] twodConv中卷积核是否一定是长宽相同的？卷积的步长是多少？

### ISSUE THREAD

**Issue by shinxg** [UCAS-IPA/IPA-discuss#3]
### 问题描述
twoConv中卷积核是否一定是长宽相同的？卷积的步长是多少？

**Comment by ijinjay** [comment]
理论上和实际上都不需要一定长宽相同，**有精力的同学**多实现几种规格的卷积核试试，奇数的，偶数的。更进一步，也有一些研究在做关于异形卷积核和可变卷积核的工作，相关研究主题为irregular convolution, deformable convolution。工业界，GoogLeNet 及Inception Resnet V2内部含有长方形卷积核。 😃 

关于步长，可以调研一下现有常用的，可以实现成变长参数，**看程序实现能力**，不做强制要求。 🍭
@shinxg

**Comment by LoYr** [comment]
卷积步长可按1处理，不过不作硬性规定，可变长处理。

**Comment by GeYangCASIA** [comment]
长宽不一定相同。-杨戈

**Comment by HuangCongQing** [comment]
所以，卷积核这个参数 要设置成大小固定还是可变的吗？只能设置成只能输入3x3的？还是3x3，5x5，3x4怎么输入都行？

**Comment by ijinjay** [comment]
见 https://github.com/UCAS-IPA/IPA-discuss/issues/6#issuecomment-536173486
大小可变，但为简单起见，本次作业假定均为奇数。
