### ISSUE TITLE
[第三次作业-问题1] 自己实现的二维DFT与numpy中提供的fft2的结果相差一个转置

### ISSUE THREAD

**Issue by WILeroy** [UCAS-IPA/IPA-discuss#36]
### 问题描述
我根据第一题的提供的方法实现了二维DFT函数（先后计算行、列的一维DFT），但是所得的结果与numpy提供的fft2函数所得的结果不一致，二者之间相差一个转置。

### 相关文件
我用于测试的是一个3*3的矩阵：[[0, 0, 0], [3, 3, 3], [0, 0, 0]]，获得结果如下：
![image](https://user-images.githubusercontent.com/3412928/66729365-81f2b380-ee7d-11e9-9ce8-3c07648bb97c.png)

**Comment by ijinjay** [comment]
matlab 和 numpy 直接调用fft2的结果都是第一种，所以应该是你的 `my dft2d` 有误。请仔细检查一下自己的代码。

**Comment by WILeroy** [comment]
好的，我明白了，我在第二次以列为单位计算一维DFT时，依旧以行为单位进行了保存。
