### ISSUE TITLE
[第二次作业-问题2] 二维高斯滤波核函数，当m为偶数时候如何处理？ 

### ISSUE THREAD

**Issue by Randomless** [UCAS-IPA/IPA-discuss#4]
### 问题描述
在实现的二维高斯滤波核函数w = gaussKernel(sig，m)中，
当m为偶数时候如何处理？ m<=2 || m为偶数 则都报错invalid number :m 是否可以呢？

**Comment by zhongliqun** [comment]
**m 必须是奇数（由高斯特性决定）**。以一维高斯为例，一维高斯函数是对称的，从中心点（最高点）开始取值，依次往两边取值，最终得到一维高斯核，所以高斯核大小一定是奇数，且以中心对称。
![gaussian-distribution](https://user-images.githubusercontent.com/55579451/65740500-8e57dc00-e11b-11e9-93ae-bf2cbc52ec14.jpg)


@ Randomless
