### ISSUE TITLE
[第二次作业-问题1]实现函数g=twodConv(f,w)，‘replicate’选项是作为参数传入吗？

### ISSUE THREAD

**Issue by yutan1997** [UCAS-IPA/IPA-discuss#5]
### 问题描述
问题1题目的描述中要求实现函数g=twodConv(f,w)，f代表灰度图片，w代表卷积核，没有给第三个参数的位置，代表选项的‘replicate‘是作为第三个参数传给函数吗？否则是如何决定选项到底是什么呢？

### 相关文件
使用[GIST](https://gist.github.com/)来上传相关的长文件，然后链接到此处。

**Comment by ijinjay** [comment]
是的，可以有其它参数，这两个参数是必要参数。好比如现代软件在迭代过程中也会有API更改的情况，但会将新参数设计为**可选参数，拥有默认值**。默认情况下只传入两个参数时，也可以进行调用。 😃
