### ISSUE TITLE
[第四次作业-问题2] 有选择的保边缘平滑法

### ISSUE THREAD

**Issue by nbl97** [UCAS-IPA/IPA-discuss#50]
请问，在对边缘像素处理时，是进行 padding 还是舍弃超出图像的部分，用在图像内的像素点算均值和方差？谢谢。

**Comment by chenyuege** [comment]
请问是进行补0还是像素复制，还是舍弃不处理

**Comment by chendianhao** [comment]
建议采用 边缘像素补零、边缘像素复制和 边缘像素不处理三种方法分别对图像进行处理，然后在实验报告中比较实验结果并进行讨论。
