### ISSUE TITLE
[第二次作业-问题1]卷积核长宽不是奇数时 取哪个作为中心点？

### ISSUE THREAD

**Issue by lijixing0425** [UCAS-IPA/IPA-discuss#6]
卷积核长宽不是奇数时 取哪个作为中心点？

**Comment by ijinjay** [comment]
视情况而定，目前大多数卷积核均为奇数，一是容易确认中心点，二是在padding时保证图像两边对称。

偶数不常见，但也有类似的例子，比如Roberts算子，选取哪一个点作为中心点视情况而定。一般可选取中心坐标的左侧或右侧一个点，也有默认采用左上角为中心点的方案，个人实现时可采用任一种并说明即可。对偶数卷积核感兴趣，可以参考如下文献：
[Convolution with even-sized kernels and symmetric padding](http://xxx.itp.ac.cn/pdf/1903.08385v2)。 😃

**Comment by GeYangCASIA** [comment]
为简单起见，这次作业我们可以直接假设卷积核长宽都是奇数。-杨戈
