### ISSUE TITLE
[第四次作业-问题2] 关于9个算子的步长问题

### ISSUE THREAD

**Issue by aiboys** [UCAS-IPA/IPA-discuss#65]
### 问题描述
对于有选择保边缘平滑法的ppt写有如图所示9个算子。
但不太清楚五边形和六边形算子在此5*5区域内的完整分布。
![protect](https://user-images.githubusercontent.com/45069071/68302917-d6382e80-00dd-11ea-9506-3091c00c7577.png)
我的猜想：
正方形算子在正中间；
四个五边形和四个六边形算子都是在该区域的“四角”？
或者说类似于一个五边形算子（or六边形算子）在该区域内是stride=2的平移分布？（手画图如下所示，粗线为六边形算子，细线为五边形算子，黑色框为正方形算子，每个不同的算子用不同颜色标记）：
![protect2](https://user-images.githubusercontent.com/45069071/68304144-22846e00-00e0-11ea-89a5-994f2b4d93f7.png)

### 相关文件
使用[GIST](https://gist.github.com/)来上传相关的长文件，然后链接到此处。

**Comment by chendianhao** [comment]
你把原图上的五边形和六边形分别绕中心点顺时针旋转 90度，180度，270.就可以得到其他的掩模了。

**Comment by aiboys** [comment]
> 你把原图上的五边形和六边形分别绕中心点顺时针旋转 90度，180度，270.就可以得到其他的掩模了。

emmmm，谢谢回复。请问这是老师上课讲的操作吗~~~

**Comment by chendianhao** [comment]
> 你把原图上的五边形和六边形分别绕中心点顺时针旋转 90度，180度，270.就可以得到其他的掩模了。
> 
> emmmm，谢谢回复。请问这是老师上课讲的操作吗~~~

嗯，我是助教。我不知道老师上课讲过没有，就算没有讲过应该也可以根据PPT推断出来。首先掩模肯定会与中心像素有接触的部分，才能体现其与中心像素的滤波关系。所以肯定就排除了你所说的平移法。其次根据PPT上讲的五边形和六边形在中心像素处有锐角，也知道掩模和中心像素有接触，并且在中心像素处为锐角。最后根据五边形和六边形的个数，各4个，很容易想到4边和4角各一个，最终判定只有旋转能够满足上述要求。不明白的时候，多看看PPT思考一下。

**Comment by chenyuege** [comment]
我怎么没想到啊，哎

**Comment by aiboys** [comment]
> > 你把原图上的五边形和六边形分别绕中心点顺时针旋转 90度，180度，270.就可以得到其他的掩模了。
> > emmmm，谢谢回复。请问这是老师上课讲的操作吗~~~
> 
> 嗯，我是助教。我不知道老师上课讲过没有，就算没有讲过应该也可以根据PPT推断出来。首先掩模肯定会与中心像素有接触的部分，才能体现其与中心像素的滤波关系。所以肯定就排除了你所说的平移法。其次根据PPT上讲的五边形和六边形在中心像素处有锐角，也知道掩模和中心像素有接触，并且在中心像素处为锐角。最后根据五边形和六边形的个数，各4个，很容易想到4边和4角各一个，最终判定只有旋转能够满足上述要求。不明白的时候，多看看PPT思考一下。

啊！谢谢。
