### ISSUE TITLE
[第二次作业-问题1]matlab函数conv2中shape参数full, same, valid取值含义与实现细节

### ISSUE THREAD

**Issue by chenyuege** [UCAS-IPA/IPA-discuss#7]
请问二维卷积得出的结果是和conv2中的“full”类型相同，怎么把结果维度改成和f一样啊

**Comment by youxiaobo** [comment]
如下图所示：
![conv](https://user-images.githubusercontent.com/29733329/65814608-aa8c7380-e216-11e9-8f4c-7ebb1d5cb62e.png)

摘自matlab：
2-D convolution, returned as a vector or matrix. When A and B are matrices, then the convolution C = conv2(A,B) has size size(A)+size(B)-1.

使用full选项时，其实现过程为：如果B的大小为m*n，对于A左右外扩(m-1)/2，上下外扩(n-1)/2，padding使用补零，再与B做卷积运算。
因此，使用full选项时，截取所得结果的中间部分作为输出即可得到和输入图像相同维度的矩阵。 😄

**Comment by chenyuege** [comment]
谢谢了
