### ISSUE TITLE
[第二次作业-问题1]边界填充

### ISSUE THREAD

**Issue by GeYangCASIA** [UCAS-IPA/IPA-discuss#8]
请注意，边界填充要求直接实现，不要调用已有的图像边界处理函数。-杨戈

**Comment by ShunLu91** [comment]
请问复制方式的边界填充是只复制最外圈的像素吗？比如我需要在图像外填充两圈边界，这两圈填充的值都是图像的最外圈的值，还是说这两圈的值分别是图像的最外圈和次外圈的值呢？

**Comment by zhongliqun** [comment]
‘replicate’是复制最近的像素灰度，因此填充的两圈像素值都参考图像最外圈。

![image](https://user-images.githubusercontent.com/55579451/65843394-0ca6bf00-e364-11e9-80a5-6a8c03bbc64a.png)

**Comment by ShunLu91** [comment]
好的，谢谢！
