### ISSUE TITLE
[第二次作业-问题3]对于σ=1 下的结果，与直接调用相关函数的结果进行比较（可以简单计算差值图像）

### ISSUE THREAD

**Issue by SCH1001** [UCAS-IPA/IPA-discuss#9]
### 问题描述
请问相关函数是什么意思？是matlab或opencv中现成的函数么？

**Comment by zhongliqun** [comment]
相关函数指matlab或opencv自带函数，matlab 有自带的高斯滤波函数，参考函数 imgaussfilt ( f,sig,'FilterSize',7,'padding',replicate) (f：输入图像，sig：标准差，'FilterSize'：卷积核尺寸，'padding'，像素填补方式)。如对函数仍有疑问，请到matlab命令窗口输入 ‘doc imgaussfilt’，查看官方介绍。
